version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - poll-network

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks:
      - poll-network

  postgres-poll:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: polls
    ports: ["5432:5432"]
    networks:
      - poll-network

  polls-service:
    build: ./polls-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-poll:5432/polls
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    ports: ["7001:7001"]
    depends_on: [postgres-poll]
    networks:
      - poll-network

  vote-publisher-service:
    build: ./vote-publisher
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      POLL_SVC_URL: http://polls-service:7001
    ports: ["7002:7002"]
    depends_on: [rabbitmq, redis]
    networks:
      - poll-network

  vote-processor:
    build: ./vote-processor
    environment:
      RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-poll:5432/polls
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
      REDIS_HOST: redis
    ports: ["7003:7003"]
    depends_on: [rabbitmq, postgres-poll, redis]
    networks:
      - poll-network

  websocket-service:
    build: ./socket-server
    environment:
      POLL_SVC_URL: http://vote-publisher-service:7002/api/v1
      RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-poll:5432/polls
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
      REDIS_HOST: redis
    ports: ["7004:7004"]
    depends_on: [rabbitmq, postgres-poll, vote-publisher-service]
    networks:
      - poll-network


networks:
  poll-network:
    driver: bridge